# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField(max_length=50)),
                ('book_id', models.IntegerField()),
                ('author', models.TextField(max_length=50)),
                ('released_date', models.DateField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
